# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: chocolina
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bonzai-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  logs:
    restAPI: true
    httpApi: true
    websocket: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:eu-north-1:*:table/BonzaiBookings

package:
  exclude:
    - '.git/**'
    - '*.log'
    - '.env'
    - 'vscode/**'
    - '.serverless/**'
    - '.gitignore'
    - 'idea/**'

functions:
  cancelBooking:
    handler: functions/cancelBooking/index.handler
    events:
      - httpApi:
          path: /bookings/cancel
          method: delete

  checkRoomAvailability:
    handler: functions/checkRoomAvailability/index.handler
    events:
      - httpApi:
          path: /bookings/available
          method: get

  createBooking:
    handler: functions/createBooking/index.handler
    events:
      - httpApi:
          path: /bookings/create
          method: post

  getAllRooms:
    handler: functions/getAllRooms/index.handler
    events:
      - httpApi:
          path: /rooms
          method: get

  getBookingById:
    handler: functions/getBookingById/index.handler
    events:
      - httpApi:
          path: /bookings/{id}
          method: get

  updateBooking:
    handler: functions/updateBooking/index.handler
    events:
      - httpApi:
          path: /bookings/update
          method: put

  verifyBooking:
    handler: functions/verifyBooking/index.handler
    events:
      - httpApi:
          path: /bookings/verify
          method: post
